### PR TITLE
Added ability to run on multiple files at once

### PR DESCRIPTION
**Pull request by voletiv**

### CODE REVIEW

**Comment by severin-lemaignan** [comment]
@voletiv thank you for your contribution. I'm happy to merge this feature, but instead of creating a new `gazr_benchmark_head_pose_multiple_frames` binary which is almost the same as the 'single file' one, could you instead add a command-line option to the 'single file' version to accept a list of files to process?

Something like:

```
./gazr_benchmark_head_pose --files frames.txt ../share/shape_predictor_68_face_landmarks.dat
```

**Comment by voletiv** [comment]
@severin-lemaignan Done! Please check.

**Comment by severin-lemaignan** [comment]
Great. Can you squash your 3 commits into a single one, and then, I'll merge your PR.

**Comment by voletiv** [comment]
Squashed, please check.

**Comment by severin-lemaignan** [comment]
Merged, thanks!

**Pull request merged**
